<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>New Contact Form Submission</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f6f8;
      margin: 0;
      padding: 0;
    }
    .email-container {
      max-width: 600px;
      margin: 40px auto;
      background-color: #ffffff;
      border-radius: 8px;
      overflow: hidden;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
    }
    .email-header {
      background-color: #003883;
      color: #ffffff;
      padding: 24px;
      text-align: center;
    }
    .email-header img {
      max-height: 40px;
      margin-bottom: 12px;
    }
    .email-body {
      padding: 24px;
      color: #333;
    }
    .email-body p {
      line-height: 1.6;
      font-size: 15px;
      margin: 12px 0;
    }
    .email-body strong {
      color: #003883;
    }
    .email-footer {
      background-color: #f0f0f0;
      padding: 16px 24px;
      text-align: center;
      font-size: 12px;
      color: #777;
    }
  </style>
</head>
<body>
  <div class="email-container">
    <div class="email-header">
      <img src="https://two025-may-enviroworks-mainapplication.onrender.com/img/eurofins-logo.png" alt="Eurofins EnviroWorks Logo">
      <h2>New Contact Form Submission</h2>
    </div>

    <div class="email-body">
      <p><span class="label">Name:</span> {{ $data['first_name'] }} {{ $data['last_name'] }}</p>
    <p><span class="label">Email:</span> {{ $data['email'] }}</p>
    <p><span class="label">Phone:</span> {{ $data['phone_number'] ?? '-' }}</p>
    <p><span class="label">City:</span> {{ $data['city'] ?? '-' }}</p>
    <p><span class="label">Province/State:</span> {{ $data['province_state'] ?? '-' }}</p>
    <p><span class="label">Message:</span><br>{{ $data['message'] }}</p>
    </div>

    <div class="email-footer">
      Eurofins EnviroWorks — This message was generated by your website's contact form.
    </div>
  </div>
</body>
</html>